
on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * 1-5"

jobs:
  get_output:
    runs-on: ubuntu-latest

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Copy'
      run: |-
        gsutil cp "${{ secrets.OUTPUT_URI }}" .

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

